name: Uptime CI
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
env:
  GH_PAT: ${{ secrets.GITHUB_TOKEN }}
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.43.6
        with:
          command: update
