name: Uptime CI
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}
jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: upptime/uptime-monitor@v1.30.0
        with:
          command: update